sonar.projectKey=CHANGE_ME_ORG_tasklist-backend
sonar.organization=CHANGE_ME_ORG
sonar.projectName=Tasklist Backend API
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.exclusions=src/__tests__/**,dist/**,coverage/**

sonar.tests=src/__tests__
sonar.test.inclusions=src/__tests__/**/*.test.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info
